import { NextResponse } from 'next/server';

export const GET = async () => {
  const rand = () => `https://picsum.photos/900/700?random=${Math.floor(Math.random() * 5000)}`;

  const caseStudies = [
    {
      title: 'Streamlining Operations for Scalable Growth',
      description: 'Helping Vertex Manufacturing achieve sustainable growth.',
      image: rand(),
      link: '/case-studies/vertex-manufacturing',
      tags: ['Operations', 'Manufacturing', 'Efficiency'],
      date: '2024-01-15',
    },
    {
      title: 'Driving Efficiency Through Digital Transformation',
      description: 'Transforming outdated systems into agile solutions.',
      image: rand(),
      link: '/case-studies/digital-transformation',
      tags: ['Technology', 'Digital', 'Automation'],
      date: '2023-11-02',
    },
    {
      title: 'Smarter Sales & Growth Strategy Rollout',
      description: 'Nationwide strategy improving lead pipeline & revenue.',
      image: rand(),
      link: '/case-studies/market-expansion',
      tags: ['Marketing', 'Sales', 'Growth'],
      date: '2023-06-12',
    },
    {
      title: 'Building Resilient Supply Chains',
      description: 'Robust supply chain automation & forecasting.',
      image: rand(),
      link: '/case-studies/supply-chain',
      tags: ['Operations', 'Supply Chain', 'Planning'],
      date: '2022-12-03',
    },
    {
      title: 'Accelerating Innovation Through Agile Practices',
      description: 'Faster sprint cycles + culture transformation.',
      image: rand(),
      link: '/case-studies/agile-innovation',
      tags: ['Technology', 'Innovation', 'Agile'],
      date: '2022-08-19',
    },
    {
      title: 'Revamping E-Commerce Checkout Experience',
      description: 'Reducing friction and boosting conversions by 41%.',
      image: rand(),
      link: '/case-studies/ecommerce',
      tags: ['UX', 'E-Commerce', 'Conversion'],
      date: '2024-02-05',
    },
    {
      title: 'B2B Lead Pipeline Optimization',
      description: 'Scaled inbound qualified leads by 3.2x in six months.',
      image: rand(),
      link: '/case-studies/b2b-pipeline',
      tags: ['Sales', 'Marketing', 'Optimization'],
      date: '2023-09-17',
    },
    {
      title: 'Smart Inventory Management Platform',
      description: 'Eliminated stockouts and reduced holding cost by 18%.',
      image: rand(),
      link: '/case-studies/inventory-management',
      tags: ['Supply Chain', 'Technology', 'AI'],
      date: '2023-04-11',
    },
    {
      title: 'Cloud Migration for Legacy Systems',
      description: 'Modernized infrastructure reducing downtime by 83%.',
      image: rand(),
      link: '/case-studies/cloud-migration',
      tags: ['Cloud', 'Technology', 'Migration'],
      date: '2022-10-22',
    },
    {
      title: 'Product-Led Growth Implementation',
      description: 'Self-serve onboarding boosted ARR without expanding sales.',
      image: rand(),
      link: '/case-studies/product-led-growth',
      tags: ['PLG', 'SaaS', 'Growth'],
      date: '2023-07-03',
    },
    {
      title: 'Customer Journey Mapping Overhaul',
      description: 'Cut churn by understanding customer experience gaps.',
      image: rand(),
      link: '/case-studies/customer-journey',
      tags: ['CX', 'Design', 'Strategy'],
      date: '2024-01-02',
    },
    {
      title: 'Automated KPI Reporting System',
      description: 'Real-time dashboards reduced reporting hours by 90%.',
      image: rand(),
      link: '/case-studies/kpi-automation',
      tags: ['Analytics', 'Automation', 'BI'],
      date: '2023-03-18',
    },
    {
      title: 'AI Chatbot for Customer Support',
      description: 'Improved response time and empowered support agents.',
      image: rand(),
      link: '/case-studies/ai-chatbot',
      tags: ['AI', 'Automation', 'Support'],
      date: '2024-03-10',
    },
    {
      title: 'Multi-Region Marketing Expansion',
      description: 'Localized campaigns increased conversion across markets.',
      image: rand(),
      link: '/case-studies/global-marketing',
      tags: ['Marketing', 'Localization', 'Growth'],
      date: '2023-10-28',
    },
    {
      title: 'Predictive Maintenance Program',
      description: 'Preventative analytics slashed downtime dramatically.',
      image: rand(),
      link: '/case-studies/predictive-maintenance',
      tags: ['Manufacturing', 'AI', 'Planning'],
      date: '2022-06-02',
    },
    {
      title: 'Sales CRM Optimization',
      description: 'Pipeline clean-up and automation improved win rate.',
      image: rand(),
      link: '/case-studies/crm-optimization',
      tags: ['Sales', 'CRM', 'Automation'],
      date: '2023-05-14',
    },
    {
      title: 'Omnichannel Retail Strategy',
      description: 'Integrated experience across stores, web, and mobile.',
      image: rand(),
      link: '/case-studies/omnichannel',
      tags: ['Retail', 'Strategy', 'Omnichannel'],
      date: '2024-02-01',
    },
    {
      title: 'Warehouse Robotics Initiative',
      description: 'Cut pick-and-pack labor time in half.',
      image: rand(),
      link: '/case-studies/warehouse-robotics',
      tags: ['Automation', 'Robotics', 'Supply Chain'],
      date: '2023-08-26',
    },
    {
      title: 'Cybersecurity Risk Assessment',
      description: 'Eliminated critical vulnerabilities across operations.',
      image: rand(),
      link: '/case-studies/cybersecurity',
      tags: ['Security', 'Technology', 'Compliance'],
      date: '2022-09-01',
    },
    {
      title: 'Mobile App Redesign + Adoption',
      description: 'Modern UI/UX increased daily active usage by 74%.',
      image: rand(),
      link: '/case-studies/mobile-app',
      tags: ['UX', 'Mobile', 'Design'],
      date: '2023-12-12',
    },
  ];

  return NextResponse.json({ caseStudies });
};
