import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClientLayout } from "@/components/ClientLayout";
import { Providers } from "@/components/Providers";
import fs from 'fs';
import path from 'path';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Load meta data dynamically
function getMetaData() {
  try {
    const metaPath = path.join(process.cwd(), 'public', 'SiteContent', 'meta.json');
    const metaData = JSON.parse(fs.readFileSync(metaPath, 'utf8'));
    return metaData;
  } catch (error) {
    console.error('Error loading meta.json:', error);
    return null;
  }
}

const metaData = getMetaData();

export const metadata: Metadata = {
  title: metaData?.seo?.title || "Create Next App",
  description: metaData?.seo?.description || "Generated by create next app",
  keywords: metaData?.seo?.keywords,
  icons: {
    icon: metaData?.seo?.favicon || '/favicon.ico',
    shortcut: metaData?.seo?.favicon || '/favicon.ico',
    apple: metaData?.seo?.favicon || '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {metaData?.seo?.themeColor && (
          <meta name="theme-color" content={metaData.seo.themeColor} />
        )}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const theme = localStorage.getItem('theme');
                const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                if (theme === 'dark' || (!theme && prefersDark)) {
                  document.documentElement.classList.add('dark');
                }
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  max-w-screen overflow-x-hidden`}
      >
        <Providers>
          <ClientLayout>
            {children}
          </ClientLayout>
        </Providers>
      </body>
    </html>
  );
}
